# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: two_phase_commit.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'two_phase_commit.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16two_phase_commit.proto\x12\x10two_phase_commit\"J\n\x0bVoteRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x11\n\toperation\x18\x02 \x01(\t\x12\x10\n\x08order_id\x18\x03 \x01(\t\"K\n\x0cVoteResponse\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x13\n\x0bvote_commit\x18\x02 \x01(\x08\x12\x0e\n\x06reason\x18\x03 \x01(\t\"g\n\x0f\x44\x65\x63isionRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12,\n\x08\x64\x65\x63ision\x18\x02 \x01(\x0e\x32\x1a.two_phase_commit.Decision\x12\x0e\n\x06reason\x18\x03 \x01(\t\"L\n\x10\x44\x65\x63isionResponse\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t*E\n\x08\x44\x65\x63ision\x12\x14\n\x10\x44\x45\x43ISION_UNKNOWN\x10\x00\x12\x11\n\rGLOBAL_COMMIT\x10\x01\x12\x10\n\x0cGLOBAL_ABORT\x10\x02\x32\xad\x01\n\x13TwoPhaseParticipant\x12\x45\n\x04Vote\x12\x1d.two_phase_commit.VoteRequest\x1a\x1e.two_phase_commit.VoteResponse\x12O\n\x06\x44\x65\x63ide\x12!.two_phase_commit.DecisionRequest\x1a\".two_phase_commit.DecisionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'two_phase_commit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DECISION']._serialized_start=380
  _globals['_DECISION']._serialized_end=449
  _globals['_VOTEREQUEST']._serialized_start=44
  _globals['_VOTEREQUEST']._serialized_end=118
  _globals['_VOTERESPONSE']._serialized_start=120
  _globals['_VOTERESPONSE']._serialized_end=195
  _globals['_DECISIONREQUEST']._serialized_start=197
  _globals['_DECISIONREQUEST']._serialized_end=300
  _globals['_DECISIONRESPONSE']._serialized_start=302
  _globals['_DECISIONRESPONSE']._serialized_end=378
  _globals['_TWOPHASEPARTICIPANT']._serialized_start=452
  _globals['_TWOPHASEPARTICIPANT']._serialized_end=625
# @@protoc_insertion_point(module_scope)
