# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

# import two_phase_commit_pb2 as two__phase__commit__pb2 
from . import two_phase_commit_pb2 as two__phase__commit__pb2 

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in two_phase_commit_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TwoPhaseParticipantStub(object):
    """----- 2PC service implemented by each participant -----
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Vote = channel.unary_unary(
                '/two_phase_commit.TwoPhaseParticipant/Vote',
                request_serializer=two__phase__commit__pb2.VoteRequest.SerializeToString,
                response_deserializer=two__phase__commit__pb2.VoteResponse.FromString,
                _registered_method=True)
        self.Decide = channel.unary_unary(
                '/two_phase_commit.TwoPhaseParticipant/Decide',
                request_serializer=two__phase__commit__pb2.DecisionRequest.SerializeToString,
                response_deserializer=two__phase__commit__pb2.DecisionResponse.FromString,
                _registered_method=True)


class TwoPhaseParticipantServicer(object):
    """----- 2PC service implemented by each participant -----
    """

    def Vote(self, request, context):
        """Phase 1: voting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Decide(self, request, context):
        """Phase 2: final decision
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TwoPhaseParticipantServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Vote': grpc.unary_unary_rpc_method_handler(
                    servicer.Vote,
                    request_deserializer=two__phase__commit__pb2.VoteRequest.FromString,
                    response_serializer=two__phase__commit__pb2.VoteResponse.SerializeToString,
            ),
            'Decide': grpc.unary_unary_rpc_method_handler(
                    servicer.Decide,
                    request_deserializer=two__phase__commit__pb2.DecisionRequest.FromString,
                    response_serializer=two__phase__commit__pb2.DecisionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'two_phase_commit.TwoPhaseParticipant', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('two_phase_commit.TwoPhaseParticipant', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TwoPhaseParticipant(object):
    """----- 2PC service implemented by each participant -----
    """

    @staticmethod
    def Vote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/two_phase_commit.TwoPhaseParticipant/Vote',
            two__phase__commit__pb2.VoteRequest.SerializeToString,
            two__phase__commit__pb2.VoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Decide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/two_phase_commit.TwoPhaseParticipant/Decide',
            two__phase__commit__pb2.DecisionRequest.SerializeToString,
            two__phase__commit__pb2.DecisionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
